### ISSUE TITLE
Add proper Wiki docs

### ISSUE THREAD

**Issue by edgar-zigis** [pnovack-gottshall/ecospace#7]
Hey there!

Thank you for this great package! I believe that the documentation or some Wiki docs could improve general experience using this tool, because it's really hard to get to understand how to input specific characters and command sequences in the beginning (even though I have read a few of your articles about the eco space algorithms, it's still not easy to get around).

I will do the PR myself if I will figure this package out  😄

**Comment by pnovack-gottshall** [comment]
Thanks for the suggestion, Edgar. There is a vignette bundled with the package that might help. You can also get it at https://cran.r-project.org/web/packages/ecospace/vignettes/ecospace.html
